#!/bin/sh

STAGED_PY_FILES=$(git diff --name-only --cached | grep ".py$")

# If no files staged, exit
if [[ "$STAGED_PY_FILES" = "" ]]; then
  exit 0
fi

echo "Running tests..."
docker-compose run --rm web python manage.py test

if [ $? != 0 ]; then
  echo "Error running Python unit tests."
  exit 1
fi

echo "Running black..."
# Run black against staged python files
docker-compose run --rm web black $STAGED_PY_FILES
# Add any changes made by black
git add $STAGED_PY_FILES --update
