#!/bin/sh

STAGED_FILES=$(git diff --name-only --cached | grep ".py$")

# If no files staged, exit
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

echo "Running black..."

docker-compose run --rm web black $STAGED_FILES
# Add any changes made by black
git add --update
